/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe.ManageMemebership;

import jframe.*;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.TableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.awt.print.PrinterException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brizu
 */
public class MembershipPayment extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MembershipPayment.class.getName());

    /**
     * Creates new form ManageOrder
     */
    public MembershipPayment() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnOnline = new rojerusan.RSMaterialButtonCircle();
        lbl_discount = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnOnsite = new rojerusan.RSMaterialButtonCircle();
        jLabel72 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOnline.setBackground(new java.awt.Color(120, 27, 27));
        btnOnline.setBorder(new javax.swing.border.MatteBorder(null));
        btnOnline.setText("ONLINE");
        btnOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineActionPerformed(evt);
            }
        });
        jPanel2.add(btnOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 160, 50));

        lbl_discount.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lbl_discount.setForeground(new java.awt.Color(120, 27, 27));
        jPanel2.add(lbl_discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 390, 110, 60));

        jLabel16.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(120, 27, 27));
        jLabel16.setText("Select Mode of Payment");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 300, 70));

        jPanel3.setBackground(new java.awt.Color(120, 27, 27));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 420, 5));

        btnOnsite.setBackground(new java.awt.Color(120, 27, 27));
        btnOnsite.setBorder(new javax.swing.border.MatteBorder(null));
        btnOnsite.setText("ONSITE");
        btnOnsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnsiteActionPerformed(evt);
            }
        });
        jPanel2.add(btnOnsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 160, 50));

        jLabel72.setBackground(new java.awt.Color(120, 27, 27));
        jLabel72.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px(redVersion).png"))); // NOI18N
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 360));

        setSize(new java.awt.Dimension(541, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineActionPerformed
        OnlinePayment online = new OnlinePayment();
        online.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOnlineActionPerformed

    private void btnOnsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnsiteActionPerformed
        OnsitePayment onsite = new OnsitePayment();
        onsite.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOnsiteActionPerformed

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
        // TODO add your handling code here:
        ManageMembership membership = new ManageMembership();
        membership.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel72MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MembershipPayment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btnOnline;
    private rojerusan.RSMaterialButtonCircle btnOnsite;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_discount;
    // End of variables declaration//GEN-END:variables
}
