/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brizu
 */
public class IssueBookDetails extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueBookDetails.class.getName());

    /**
     * Creates new form IssueBookDetails
     */
    DefaultTableModel model;

    public IssueBookDetails() {
        initComponents();
        setPendingBookDetails();
        setOverdueBookDetails();
    }

    // inputs the pending book details in the table
    public void setPendingBookDetails() {
        try (Connection con = DBConnection.getConnection(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery("SELECT * FROM issue_book_details WHERE status = 'pending'")) {

            while (rs.next()) {
                String id = rs.getString("id");
                String bookName = rs.getString("book_name");
                String userId = rs.getString("user_id");

                String issueDate = rs.getString("issue_date");
                String dueDate = rs.getString("due_date");
                String status = rs.getString("status");

                Object[] obj = {id, bookName, userId, issueDate, dueDate, status};
                model = (DefaultTableModel) tbl_pendingBookDetails.getModel();
                model.addRow(obj);
            }
        } catch (Exception e) {
            logger.severe("Error loading pending book details: " + e.getMessage());
        }
    }

    // inputs the overdue book details in the table
    public void setOverdueBookDetails() {
        long l = System.currentTimeMillis();
        Date currentDate = new Date(l);

        try (Connection con = DBConnection.getConnection(); PreparedStatement pst = con.prepareStatement("SELECT * FROM issue_book_details WHERE due_date < ? AND status = ?")) {

            pst.setDate(1, currentDate);
            pst.setString(2, "pending");

            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    String id = rs.getString("id");
                    String bookName = rs.getString("book_name");
                    String userId = rs.getString("user_id");

                    String issueDate = rs.getString("issue_date");
                    String dueDate = rs.getString("due_date");
                    String status = rs.getString("status");

                    Object[] obj = {id, bookName, userId, issueDate, dueDate, status};
                    model = (DefaultTableModel) tbl_overdueBookDetails.getModel();
                    model.addRow(obj);
                }
            }
        } catch (Exception e) {
            logger.severe("Error loading overdue book details: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pendingBookDetails = new rojeru_san.complementos.RSTableMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_issueBookDetails2 = new rojeru_san.complementos.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_overdueBookDetails = new rojeru_san.complementos.RSTableMetro();
        jPanel36 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(120, 27, 27));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 340, 5));

        jLabel72.setBackground(new java.awt.Color(120, 27, 27));
        jLabel72.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px(redVersion).png"))); // NOI18N
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 70));

        tbl_pendingBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "User Id", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_pendingBookDetails.setColorBackgoundHead(new java.awt.Color(120, 27, 27));
        tbl_pendingBookDetails.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_pendingBookDetails.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_pendingBookDetails.setColorSelBackgound(new java.awt.Color(153, 0, 0));
        tbl_pendingBookDetails.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tbl_pendingBookDetails.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tbl_pendingBookDetails.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tbl_pendingBookDetails.setFuenteHead(new java.awt.Font("Serif", 1, 20)); // NOI18N
        tbl_pendingBookDetails.setRowHeight(40);
        tbl_pendingBookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pendingBookDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_pendingBookDetails);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 640, 320));

        tbl_issueBookDetails2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "User Name", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_issueBookDetails2.setColorBackgoundHead(new java.awt.Color(120, 27, 27));
        tbl_issueBookDetails2.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_issueBookDetails2.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_issueBookDetails2.setColorSelBackgound(new java.awt.Color(153, 0, 0));
        tbl_issueBookDetails2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tbl_issueBookDetails2.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tbl_issueBookDetails2.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tbl_issueBookDetails2.setFuenteHead(new java.awt.Font("Serif", 1, 20)); // NOI18N
        tbl_issueBookDetails2.setRowHeight(40);
        tbl_issueBookDetails2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_issueBookDetails2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_issueBookDetails2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 640, 320));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(120, 27, 27));
        jLabel2.setText("    Pending Book Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 260, -1));

        jPanel35.setBackground(new java.awt.Color(120, 27, 27));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 340, 5));

        tbl_overdueBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "User Id", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_overdueBookDetails.setColorBackgoundHead(new java.awt.Color(120, 27, 27));
        tbl_overdueBookDetails.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_overdueBookDetails.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_overdueBookDetails.setColorSelBackgound(new java.awt.Color(153, 0, 0));
        tbl_overdueBookDetails.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tbl_overdueBookDetails.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tbl_overdueBookDetails.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tbl_overdueBookDetails.setFuenteHead(new java.awt.Font("Serif", 1, 20)); // NOI18N
        tbl_overdueBookDetails.setRowHeight(40);
        tbl_overdueBookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_overdueBookDetailsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_overdueBookDetails);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 640, 320));

        jPanel36.setBackground(new java.awt.Color(120, 27, 27));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 340, 5));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(120, 27, 27));
        jLabel3.setText("    Overdue Book Details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 660));

        setSize(new java.awt.Dimension(1376, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel72MouseClicked

    private void tbl_pendingBookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pendingBookDetailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_pendingBookDetailsMouseClicked

    private void tbl_issueBookDetails2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_issueBookDetails2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_issueBookDetails2MouseClicked

    private void tbl_overdueBookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_overdueBookDetailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_overdueBookDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueBookDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private rojeru_san.complementos.RSTableMetro tbl_issueBookDetails2;
    private rojeru_san.complementos.RSTableMetro tbl_overdueBookDetails;
    private rojeru_san.complementos.RSTableMetro tbl_pendingBookDetails;
    // End of variables declaration//GEN-END:variables
}
