/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author brizu
 */
public class IssueBook extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueBook.class.getName());
    
    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    
    }
    
    //to fetch the book details from the database and display it to book details panel
    public void getBookDetails(){
        int bookId = Integer.parseInt(txt_bookId.getText());
        
        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from book_details where book_id = ?");
            pst.setInt(1, bookId);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                lbl_bookId.setText(rs.getString("book_id"));
                lbl_bookName.setText(rs.getString("book_name"));
                lbl_author.setText(rs.getString("author"));
                lbl_quantity.setText(rs.getString("quantity")); 
                lbl_bookPrice.setText(rs.getString("book_price"));
            }
                
        } catch (Exception e) {
            e.getStackTrace();
        }
    }

    //to fetch the user details from the database and display it to user details panel
    public void getUserDetails(){
        int userId = Integer.parseInt(txt_userId.getText());
        
        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from user_details where user_id = ?");
            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                lbl_userId.setText(rs.getString("user_id"));
                lbl_userName.setText(rs.getString("name"));
                lbl_membershipType.setText(rs.getString("membership_type"));
            }
                
        } catch (Exception e) {
            e.getStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_bookPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_bookId = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_quantity = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        lbl_userId = new javax.swing.JLabel();
        lbl_userName = new javax.swing.JLabel();
        lbl_membershipType = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel135 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel146 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel157 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel168 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        txt_bookId = new app.bolivia.swing.JCTextField();
        jLabel92 = new javax.swing.JLabel();
        txt_userId = new app.bolivia.swing.JCTextField();
        jLabel93 = new javax.swing.JLabel();
        date_issueDate = new rojeru_san.componentes.RSDateChooser();
        jLabel96 = new javax.swing.JLabel();
        date_dueDate = new rojeru_san.componentes.RSDateChooser();
        jLabel98 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(120, 27, 27));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel2.setText("    Book Details");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        lbl_bookPrice.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_bookPrice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_bookPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Name : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Author : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Book Id : ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        lbl_bookId.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_bookId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        lbl_bookName.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        lbl_author.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_author.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        lbl_quantity.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_quantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel4.setBackground(new java.awt.Color(120, 27, 27));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel13.setText("    Book Details");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price : ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel16.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Book Name : ");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Author : ");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel18.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Quantity :");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel19.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Book Id : ");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel20.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel21.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel22.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel23.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel6.setBackground(new java.awt.Color(120, 27, 27));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel24.setText("    Book Details");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel25.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Price : ");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel26.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel27.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Book Name : ");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel28.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Author : ");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel29.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Quantity :");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel30.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Book Id : ");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel31.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel32.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel33.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel34.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel8.setBackground(new java.awt.Color(120, 27, 27));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel35.setText("    Book Details");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel36.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Price : ");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel37.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel38.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Book Name : ");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel39.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Author : ");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel40.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Quantity :");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel41.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Book Id : ");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel42.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel43.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel44.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel45.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel10.setBackground(new java.awt.Color(120, 27, 27));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel46.setText("    Book Details");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel47.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Price : ");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel48.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel49.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Book Name : ");
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel50.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Author : ");
        jPanel10.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel51.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Quantity :");
        jPanel10.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel52.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Book Id : ");
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel53.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel54.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel55.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel56.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel12.setBackground(new java.awt.Color(120, 27, 27));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel57.setText("    Book Details");
        jPanel12.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel58.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Price : ");
        jPanel12.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel59.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel60.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Book Name : ");
        jPanel12.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel61.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Author : ");
        jPanel12.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel62.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Quantity :");
        jPanel12.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel63.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Book Id : ");
        jPanel12.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel64.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel65.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel66.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel67.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel14.setBackground(new java.awt.Color(120, 27, 27));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel68.setText("    Book Details");
        jPanel14.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel69.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Price : ");
        jPanel14.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel70.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel71.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Book Name : ");
        jPanel14.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel73.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Author : ");
        jPanel14.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel74.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Quantity :");
        jPanel14.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel75.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Book Id : ");
        jPanel14.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel76.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel77.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel78.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel79.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel16.setBackground(new java.awt.Color(120, 27, 27));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel80.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel80.setText("    Book Details");
        jPanel16.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel81.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Price : ");
        jPanel16.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel82.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel83.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Book Name : ");
        jPanel16.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel84.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Author : ");
        jPanel16.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel85.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Quantity :");
        jPanel16.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel86.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Book Id : ");
        jPanel16.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel87.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel88.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel89.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel90.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel10.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        panel_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 420, 820));

        jPanel18.setBackground(new java.awt.Color(120, 27, 27));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel91.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/userIcon.png"))); // NOI18N
        jLabel91.setText("    User Details");
        jPanel18.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel94.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("User Name : ");
        jPanel18.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel95.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("Membership Type : ");
        jPanel18.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel97.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("User Id : ");
        jPanel18.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        lbl_userId.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_userId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.add(lbl_userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        lbl_userName.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_userName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.add(lbl_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        lbl_membershipType.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_membershipType.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.add(lbl_membershipType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 180, 30));

        jPanel20.setBackground(new java.awt.Color(120, 27, 27));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel102.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel102.setText("    Book Details");
        jPanel20.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel103.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("Price : ");
        jPanel20.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel104.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel105.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setText("Book Name : ");
        jPanel20.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel106.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setText("Author : ");
        jPanel20.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel107.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("Quantity :");
        jPanel20.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel108.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("Book Id : ");
        jPanel20.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel109.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel110.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel111.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel112.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel22.setBackground(new java.awt.Color(120, 27, 27));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel113.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 255, 255));
        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel113.setText("    Book Details");
        jPanel22.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel114.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 255, 255));
        jLabel114.setText("Price : ");
        jPanel22.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel115.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel116.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(255, 255, 255));
        jLabel116.setText("Book Name : ");
        jPanel22.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel117.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(255, 255, 255));
        jLabel117.setText("Author : ");
        jPanel22.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel118.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(255, 255, 255));
        jLabel118.setText("Quantity :");
        jPanel22.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel119.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(255, 255, 255));
        jLabel119.setText("Book Id : ");
        jPanel22.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel120.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel121.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel122.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel123.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel24.setBackground(new java.awt.Color(120, 27, 27));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel124.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(255, 255, 255));
        jLabel124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel124.setText("    Book Details");
        jPanel24.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel125.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(255, 255, 255));
        jLabel125.setText("Price : ");
        jPanel24.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel126.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel127.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 255));
        jLabel127.setText("Book Name : ");
        jPanel24.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel128.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 255, 255));
        jLabel128.setText("Author : ");
        jPanel24.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel129.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(255, 255, 255));
        jLabel129.setText("Quantity :");
        jPanel24.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel130.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(255, 255, 255));
        jLabel130.setText("Book Id : ");
        jPanel24.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel131.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel132.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel132.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel133.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel134.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel22.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel18.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel26.setBackground(new java.awt.Color(120, 27, 27));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel135.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(255, 255, 255));
        jLabel135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel135.setText("    Book Details");
        jPanel26.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel136.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(255, 255, 255));
        jLabel136.setText("Price : ");
        jPanel26.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel137.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel137.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel138.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 255, 255));
        jLabel138.setText("Book Name : ");
        jPanel26.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel139.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel139.setText("Author : ");
        jPanel26.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel140.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(255, 255, 255));
        jLabel140.setText("Quantity :");
        jPanel26.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel141.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 255, 255));
        jLabel141.setText("Book Id : ");
        jPanel26.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel142.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel143.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel144.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel145.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel28.setBackground(new java.awt.Color(120, 27, 27));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel146.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(255, 255, 255));
        jLabel146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel146.setText("    Book Details");
        jPanel28.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel147.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel147.setForeground(new java.awt.Color(255, 255, 255));
        jLabel147.setText("Price : ");
        jPanel28.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel148.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel149.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(255, 255, 255));
        jLabel149.setText("Book Name : ");
        jPanel28.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel150.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(255, 255, 255));
        jLabel150.setText("Author : ");
        jPanel28.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel151.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(255, 255, 255));
        jLabel151.setText("Quantity :");
        jPanel28.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel152.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(255, 255, 255));
        jLabel152.setText("Book Id : ");
        jPanel28.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel153.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel153.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel154.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel155.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel155.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel156.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel30.setBackground(new java.awt.Color(120, 27, 27));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel157.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(255, 255, 255));
        jLabel157.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel157.setText("    Book Details");
        jPanel30.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel158.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(255, 255, 255));
        jLabel158.setText("Price : ");
        jPanel30.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel159.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel159.setForeground(new java.awt.Color(255, 255, 255));
        jPanel30.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel160.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(255, 255, 255));
        jLabel160.setText("Book Name : ");
        jPanel30.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel161.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel161.setForeground(new java.awt.Color(255, 255, 255));
        jLabel161.setText("Author : ");
        jPanel30.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel162.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(255, 255, 255));
        jLabel162.setText("Quantity :");
        jPanel30.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel163.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel163.setForeground(new java.awt.Color(255, 255, 255));
        jLabel163.setText("Book Id : ");
        jPanel30.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel164.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel164.setForeground(new java.awt.Color(255, 255, 255));
        jPanel30.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel165.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel165.setForeground(new java.awt.Color(255, 255, 255));
        jPanel30.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel166.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel166.setForeground(new java.awt.Color(255, 255, 255));
        jPanel30.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel167.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel167.setForeground(new java.awt.Color(255, 255, 255));
        jPanel30.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel32.setBackground(new java.awt.Color(120, 27, 27));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel168.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel168.setForeground(new java.awt.Color(255, 255, 255));
        jLabel168.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel168.setText("    Book Details");
        jPanel32.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, -1));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 5));

        jLabel169.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel169.setForeground(new java.awt.Color(255, 255, 255));
        jLabel169.setText("Price : ");
        jPanel32.add(jLabel169, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel170.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel170.setForeground(new java.awt.Color(255, 255, 255));
        jPanel32.add(jLabel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 230, 30));

        jLabel171.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel171.setForeground(new java.awt.Color(255, 255, 255));
        jLabel171.setText("Book Name : ");
        jPanel32.add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel172.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel172.setForeground(new java.awt.Color(255, 255, 255));
        jLabel172.setText("Author : ");
        jPanel32.add(jLabel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel173.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel173.setForeground(new java.awt.Color(255, 255, 255));
        jLabel173.setText("Quantity :");
        jPanel32.add(jLabel173, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel174.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel174.setForeground(new java.awt.Color(255, 255, 255));
        jLabel174.setText("Book Id : ");
        jPanel32.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel175.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel175.setForeground(new java.awt.Color(255, 255, 255));
        jPanel32.add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 30));

        jLabel176.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel176.setForeground(new java.awt.Color(255, 255, 255));
        jPanel32.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 230, 30));

        jLabel177.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel177.setForeground(new java.awt.Color(255, 255, 255));
        jPanel32.add(jLabel177, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, 30));

        jLabel178.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel178.setForeground(new java.awt.Color(255, 255, 255));
        jPanel32.add(jLabel178, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 230, 30));

        jPanel30.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel26.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        jPanel18.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 420, 810));

        panel_main.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 420, 820));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(120, 27, 27));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel1.setText("Issue Book");
        panel_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, -1));

        jLabel72.setBackground(new java.awt.Color(120, 27, 27));
        jLabel72.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px(redVersion).png"))); // NOI18N
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        panel_main.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 70));

        jPanel34.setBackground(new java.awt.Color(120, 27, 27));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_main.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 240, 5));

        txt_bookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(120, 27, 27)));
        txt_bookId.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        txt_bookId.setPhColor(new java.awt.Color(120, 27, 27));
        txt_bookId.setPlaceholder("Enter Book Id....");
        txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIdFocusLost(evt);
            }
        });
        txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIdActionPerformed(evt);
            }
        });
        panel_main.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 360, 40));

        jLabel92.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(120, 27, 27));
        jLabel92.setText("Book Id : ");
        panel_main.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 70, -1));

        txt_userId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(120, 27, 27)));
        txt_userId.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        txt_userId.setPhColor(new java.awt.Color(120, 27, 27));
        txt_userId.setPlaceholder("Enter User Id....");
        txt_userId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userIdFocusLost(evt);
            }
        });
        txt_userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userIdActionPerformed(evt);
            }
        });
        panel_main.add(txt_userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 360, 40));

        jLabel93.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(120, 27, 27));
        jLabel93.setText("Issue Date : ");
        panel_main.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 90, -1));

        date_issueDate.setColorBackground(new java.awt.Color(120, 27, 27));
        date_issueDate.setColorButtonHover(new java.awt.Color(120, 27, 27));
        date_issueDate.setColorDiaActual(new java.awt.Color(120, 27, 27));
        date_issueDate.setColorForeground(new java.awt.Color(120, 27, 27));
        date_issueDate.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        date_issueDate.setFormatoFecha("dd/MM/yyyy");
        date_issueDate.setFuente(new java.awt.Font("Serif", 1, 17)); // NOI18N
        date_issueDate.setPlaceholder("Select Issue Date....");
        panel_main.add(date_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 360, -1));

        jLabel96.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(120, 27, 27));
        jLabel96.setText("User Id : ");
        panel_main.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 70, -1));

        date_dueDate.setColorBackground(new java.awt.Color(120, 27, 27));
        date_dueDate.setColorButtonHover(new java.awt.Color(120, 27, 27));
        date_dueDate.setColorDiaActual(new java.awt.Color(120, 27, 27));
        date_dueDate.setColorForeground(new java.awt.Color(120, 27, 27));
        date_dueDate.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        date_dueDate.setFormatoFecha("dd/MM/yyyy");
        date_dueDate.setFuente(new java.awt.Font("Serif", 1, 17)); // NOI18N
        date_dueDate.setPlaceholder("Select Due Date....");
        panel_main.add(date_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 360, -1));

        jLabel98.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(120, 27, 27));
        jLabel98.setText("Due Date : ");
        panel_main.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 90, -1));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(120, 27, 27));
        rSMaterialButtonCircle3.setBorder(new javax.swing.border.MatteBorder(null));
        rSMaterialButtonCircle3.setText("ISSUE BOOK");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        panel_main.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 420, 60));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 820));
        panel_main.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1411, 803));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel72MouseClicked

    private void txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIdFocusLost
        if (!txt_bookId.getText().equals("")) {
            getBookDetails();
        }
    }//GEN-LAST:event_txt_bookIdFocusLost

    private void txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdActionPerformed

    private void txt_userIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userIdFocusLost
        if (!txt_userId.getText().equals("")) {
            getUserDetails();
        }
    }//GEN-LAST:event_txt_userIdFocusLost

    private void txt_userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userIdActionPerformed

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueBook().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser date_dueDate;
    private rojeru_san.componentes.RSDateChooser date_issueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_bookId;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_bookPrice;
    private javax.swing.JLabel lbl_membershipType;
    private javax.swing.JLabel lbl_quantity;
    private javax.swing.JLabel lbl_userId;
    private javax.swing.JLabel lbl_userName;
    private javax.swing.JPanel panel_main;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private app.bolivia.swing.JCTextField txt_bookId;
    private app.bolivia.swing.JCTextField txt_userId;
    // End of variables declaration//GEN-END:variables
}
